version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - FRONTEND_ORIGIN=http://localhost:5173
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - VITE_API_URL=http://localhost:3000
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  redis-data:




